/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OneTapiRouteImport } from './routes/one-tapi'
import { Route as SuratRouteImport } from './routes/surat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OneTapiRoute = OneTapiRouteImport.update({
  id: '/one-tapi',
  path: '/one-tapi',
  getParentRoute: () => rootRouteImport,
} as any)
const SuratRoute = SuratRouteImport.update({
  id: '/surat',
  path: '/surat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/one-tapi': typeof OneTapiRoute
  '/surat': typeof SuratRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/one-tapi': typeof OneTapiRoute
  '/surat': typeof SuratRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/one-tapi': typeof OneTapiRoute
  '/surat': typeof SuratRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/one-tapi' | '/surat'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/one-tapi' | '/surat'
  id: '__root__' | '/' | '/one-tapi' | '/surat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OneTapiRoute: typeof OneTapiRoute
  SuratRoute: typeof SuratRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/one-tapi': {
      id: '/one-tapi'
      path: '/one-tapi'
      fullPath: '/one-tapi'
      preLoaderRoute: typeof OneTapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surat': {
      id: '/surat'
      path: '/surat'
      fullPath: '/surat'
      preLoaderRoute: typeof SuratRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OneTapiRoute: OneTapiRoute,
  SuratRoute: SuratRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
